!*****************************************************
!PROGRAM THAT RETURNS THE NUMBER OF DIGITS IN A NUMBER
!USING A CASE STATEMENT WITH 4 POSSIBLE OUTCOMES
!*****************************************************

IMPLICIT NONE
INTEGER NUMBER, DIGITS

READ(*, *) NUMBER
NUMBER = ABS(NUMBER)

IF (NUMBER > 9999) STOP 'NUMBER TOO LARGE'
SELECT CASE (NUMBER)
	CASE (1000:)
		DIGITS = 4
	CASE (100:999)
		DIGITS = 3
	CASE (10:99)
		DIGITS = 2
	CASE DEFAULT
		DIGITS = 1
ENDSELECT

WRITE(*, *) 'NUMBER', NUMBER, 'HAS', DIGITS, 'DIGITS'
END
